modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/shedaniel/rare-ice/issues/"
logoFile="icon.png"
authors="shedaniel"
license="Creative Commons Attribution-NonCommercial 4.0 International Public License"
[[mods]]
    modId="rare_ice"
    version="${file.jarVersion}"
    displayName="Rare Ice"
    description='''
Adds rare ice into the world. Can you find them?
'''